(() => {
  'use strict';
  const KEY = 'ease-data-v1';
  const SECTIONS = ['Early Morning','Mid Morning','Late Morning','Early Afternoon','Late Afternoon','Evening','Night'];
  const SECTION_HOURS = {
    'Early Morning':['7 AM','8 AM'], 'Mid Morning':['9 AM','10 AM'], 'Late Morning':['11 AM','12 PM'],
    'Early Afternoon':['1 PM','2 PM'], 'Late Afternoon':['3 PM','4 PM'], 'Evening':['5 PM','6 PM'], 'Night':['7 PM','8 PM']
  };
  const $ = s => document.querySelector(s);
  const uid = () => crypto.randomUUID ? crypto.randomUUID() : Date.now().toString(36)+Math.random().toString(36).slice(2);
  const today = () => new Date().toISOString().slice(0,10);
  const addDays = (date,n) => { const d=new Date(date+'T12:00:00'); d.setDate(d.getDate()+n); return d.toISOString().slice(0,10); };
  const prettyDate = d => new Date(d+'T12:00:00').toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'});
  const timeSection = () => { const h=new Date().getHours(); return h<7||h>=21?6:h<9?0:h<11?1:h<13?2:h<15?3:h<17?4:h<19?5:6; };
  const sample = () => ({tasks:[
    {id:uid(),title:'Move my body',kind:'priority',createdAt:today(),completed:[]},
    {id:uid(),title:'Dishes',kind:'rhythm',homeSection:'Early Morning',lane:'bottom',createdAt:today(),completed:[]},
    {id:uid(),title:'Reflect',kind:'rhythm',homeSection:'Evening',lane:'top',createdAt:today(),completed:[]},
    {id:uid(),title:'Check mail',kind:'recurring',date:today(),cadence:'weekly',homeSection:'',lane:'top',createdAt:today(),completed:[]}
  ],placements:{},version:1});
  let state;
  let revealSection = null;
  try { state=JSON.parse(localStorage.getItem(KEY)) || sample(); } catch { state=sample(); }
  const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
  const completed=t=>t.completed?.includes(today());
  const due=t=> { if(t.kind==='priority'||t.kind==='rhythm') return true; return !!t.date && t.date<=today(); };
  const active=t=>due(t)&&!completed(t);
  const placement=t=>state.placements[today()]?.[t.id];
  const isInRhythm=t=>!!placement(t) || t.kind==='rhythm';
  const getTasks=(kind)=>state.tasks.filter(t=>t.kind===kind&&active(t)&&!isInRhythm(t));
  let toastTimer;
  function toast(message,undo){const el=$('#toast');clearTimeout(toastTimer);el.textContent='';const text=document.createElement('span');text.textContent=message;el.append(text);if(undo){const button=document.createElement('button');button.textContent='Undo';button.className='toast-undo';button.onclick=()=>{clearTimeout(toastTimer);undo();};el.append(button)}el.classList.add('show');toastTimer=setTimeout(()=>el.classList.remove('show'),undo?6000:2100)}
  function sectionFor(t){return placement(t)?.section||t.homeSection}
  function laneFor(t){return placement(t)?.lane||t.lane||'top'}
  function overdue(t){return (t.kind==='scheduled'||t.kind==='recurring')&&t.date<today()}
  const cadenceLabel=t=>({daily:'daily',weekdays:'every weekday',weekends:'every weekend day',weekly:'weekly',biweekly:'every 2 weeks',monthly:'monthly',quarterly:'every 3 months',yearly:'yearly',custom:`every ${t.customDays||1} days`}[t.cadence]||'');
  function label(t){ if(overdue(t))return `<span class="past-tag">Past due · ${prettyDate(t.date)}</span>`; if(t.kind==='scheduled')return t.time?`${prettyDate(t.date)} · ${t.time}`:prettyDate(t.date); if(t.kind==='recurring')return t.cadence?`${cadenceLabel(t)} · due ${prettyDate(t.date)}`:`due ${prettyDate(t.date)}`; return t.kind==='priority'?'Returns tomorrow':'Daily rhythm'; }
  function taskHtml(t, inRhythm=false){const p=placement(t);const children=state.tasks.filter(x=>placement(x)?.merge===t.id&&active(x));const reschedule=(t.kind==='scheduled'||t.kind==='recurring')?`<button class="reschedule" aria-label="Reschedule ${escape(t.title)}" title="Reschedule">↪</button>`:'';const mergeDrop=inRhythm?'<span class="merge-drop" aria-label="Drop here to merge">⊕</span>':'';return `<article class="task ${overdue(t)?'past':''} ${children.length?'merged':''}" draggable="true" data-id="${t.id}"><input class="check" type="checkbox" aria-label="Complete ${escape(t.title)}"><div class="task-text"><div class="task-title">${escape(t.title)}</div><div class="task-meta">${label(t)}</div>${children.length?`<div class="merge-note">Today with: ${children.map(x=>escape(x.title)).join(', ')}</div>`:''}</div>${mergeDrop}${reschedule}<span class="drag-handle" role="button" aria-label="Hold and drag ${escape(t.title)}" title="Hold and drag">⠿</span><button class="more" aria-label="More options">•••</button></article>`}
  const escape=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  function listHtml(tasks, empty){return tasks.length?tasks.map(t=>taskHtml(t)).join(''):`<div class="empty">${empty}</div>`}
  function render(){const now=timeSection(), activeCount=state.tasks.filter(active).length;$('#app').innerHTML=`
    <header class="topbar"><div class="brandline"><div><div class="brand">Ease</div><div class="date-label">${new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})}</div></div><button class="add" id="addTask" aria-label="Add a task">+</button></div></header>
    <section class="rhythm-header"><div><h2>Day Rhythm</h2><p>${SECTIONS[now]} · ${activeCount} things available today</p></div><button class="jump" id="addRhythm">Add rhythm</button></section>
    <div id="rhythm">${SECTIONS.map((section,i)=>rhythmHtml(section,i===now)).join('')}</div>
    <div class="quad-grid">
      <section class="quadrant"><div class="quad-title"><span>Priorities</span><span class="count">${getTasks('priority').length} active</span></div><div class="task-list drop-zone" data-zone="priority">${listHtml(getTasks('priority'),'Your few important things live here.')}</div></section>
      <section class="quadrant"><div class="quad-title"><span>Scheduled priorities</span><span class="count">today</span></div><div class="task-list drop-zone" data-zone="scheduled">${listHtml(getTasks('scheduled'),'Nothing scheduled for today.')}</div></section>
      <section class="quadrant"><div class="quad-title"><span>Recurring tasks</span><span class="count">due today</span></div><div class="task-list drop-zone" data-zone="recurring">${listHtml(getTasks('recurring'),'No recurring tasks due today.')}</div></section>
    </div>`;
    bind();
    const rhythmPane=$('#rhythm');const sectionToShow=revealSection||SECTIONS[now];const target=document.getElementById('section-'+sectionToShow.replaceAll(' ','-'));const revealed=revealSection;revealSection=null;setTimeout(()=>{if(target&&rhythmPane)rhythmPane.scrollTo({top:Math.max(0,target.offsetTop-8),behavior:revealed?'smooth':'auto'});if(revealed)toast(`Added to ${revealed}`)},80);
  }
  function rhythmHtml(section, now){const tasks=state.tasks.filter(t=>active(t)&&isInRhythm(t)&&sectionFor(t)===section&&!placement(t)?.merge);const lane=n=>tasks.filter(t=>laneFor(t)===n);return `<section class="rhythm ${now?'now':''}" id="section-${section.replaceAll(' ','-')}"><h3 class="rhythm-name">${section}</h3>${['top','bottom'].map((l,i)=>`<div class="lane drop-zone" data-section="${section}" data-lane="${l}"><div class="lane-label">${SECTION_HOURS[section][i]}</div><div class="task-list">${lane(l).map(t=>taskHtml(t,true)).join('')}</div></div>`).join('')}</section>`}
  function complete(id){const root=state.tasks.find(t=>t.id===id);if(!root)return;const ids=[id,...state.tasks.filter(t=>placement(t)?.merge===id).map(t=>t.id)];const before=ids.map(x=>{const t=state.tasks.find(y=>y.id===x);return{id:x,completed:[...(t.completed||[])],date:t.date}});ids.forEach(x=>{const t=state.tasks.find(y=>y.id===x);t.completed=[...(t.completed||[]),today()];if(t.kind==='recurring')t.date=nextDate(t.date,t.cadence,t.customDays);});save();render();toast(ids.length>1?'Merged activity completed':'Done for today',()=>{before.forEach(snapshot=>{const t=state.tasks.find(x=>x.id===snapshot.id);if(t){t.completed=snapshot.completed;t.date=snapshot.date}});save();render();toast('Task restored')});}
  const nextMatchingDate=(date,match)=>{let d=new Date(date+'T12:00:00');do{d.setDate(d.getDate()+1)}while(!match(d));return d.toISOString().slice(0,10)};
  const nextMatchingOnOrAfter=(date,match)=>{let d=new Date(date+'T12:00:00');while(!match(d))d.setDate(d.getDate()+1);return d.toISOString().slice(0,10)};
  function nextDate(date,cadence,customDays=1){if(cadence==='daily')return addDays(date,1);if(cadence==='weekdays')return nextMatchingDate(date,d=>d.getDay()>0&&d.getDay()<6);if(cadence==='weekends')return nextMatchingDate(date,d=>d.getDay()===0||d.getDay()===6);if(cadence==='weekly')return addDays(date,7);if(cadence==='biweekly')return addDays(date,14);if(cadence==='custom')return addDays(date,Math.max(1,Number(customDays)||1));if(cadence==='monthly') {let d=new Date(date+'T12:00:00');d.setMonth(d.getMonth()+1);return d.toISOString().slice(0,10)}if(cadence==='quarterly')return addDays(date,91);if(cadence==='yearly'){let d=new Date(date+'T12:00:00');d.setFullYear(d.getFullYear()+1);return d.toISOString().slice(0,10)}return date;}
  function move(id,zone,section,lane,target){const t=state.tasks.find(x=>x.id===id);if(!t)return;if(target&&target!==id&&section){state.placements[today()]??={};state.placements[today()][id]={section,lane,merge:target};toast('Combined for today');}else if(target&&target!==id){const from=state.tasks.indexOf(t),to=state.tasks.findIndex(x=>x.id===target);state.tasks.splice(from,1);state.tasks.splice(from<to?to-1:to,0,t);if(t.kind==='rhythm'){t.kind='priority';t.homeSection='';}delete state.placements[today()]?.[id];if(zone&&zone!=='priority')t.kind=zone;toast('Reordered');}else if(section){state.placements[today()]??={};state.placements[today()][id]={section,lane};toast(`Moved to ${section}`)}else{if(t.kind==='rhythm'){t.kind='priority';t.homeSection='';}delete state.placements[today()]?.[id];if(zone&&zone!=='priority')t.kind=zone;toast('Moved to quadrant');}save();render();}
  function bind(){
    $('#addTask').onclick=()=>showForm();$('#addRhythm').onclick=()=>showForm({kind:'rhythm'});
    document.querySelectorAll('.check').forEach(el=>el.onchange=e=>complete(e.target.closest('.task').dataset.id));
    document.querySelectorAll('.more').forEach(el=>el.onclick=e=>{e.stopPropagation();showMenu(e.target.closest('.task').dataset.id)});
    document.querySelectorAll('.reschedule').forEach(el=>el.onclick=e=>{e.stopPropagation();showReschedule(e.target.closest('.task').dataset.id)});
    setupDrag();
  }
  let dragging=null, ghost=null;
  function setupDrag(){document.querySelectorAll('.task').forEach(el=>{el.addEventListener('dragstart',e=>{dragging=el.dataset.id;el.classList.add('dragging');e.dataTransfer.effectAllowed='move'});el.addEventListener('dragend',()=>{el.classList.remove('dragging');dragging=null;clearOver()});});document.querySelectorAll('.drag-handle').forEach(handle=>handle.addEventListener('pointerdown',pointerStart));document.querySelectorAll('.drop-zone').forEach(z=>{z.addEventListener('dragover',e=>{e.preventDefault();z.classList.add('drag-target')});z.addEventListener('dragleave',()=>z.classList.remove('drag-target'));z.addEventListener('drop',e=>{e.preventDefault();const target=e.target.closest('.merge-drop')?.closest('.task');move(dragging,z.dataset.zone,z.dataset.section,z.dataset.lane,target?.dataset.id);});});}
  function clearOver(){document.querySelectorAll('.drag-target,.over').forEach(x=>x.classList.remove('drag-target','over'));if(ghost){ghost.remove();ghost=null}}
  function pointerStart(e){const el=e.currentTarget.closest('.task'),id=el.dataset.id,startX=e.clientX,startY=e.clientY,isTouch=e.pointerType==='touch';let draggingNow=false,holdTimer=null,scrollSpeed=0,scrollFrame=null;const stopAutoScroll=()=>{scrollSpeed=0;if(scrollFrame){cancelAnimationFrame(scrollFrame);scrollFrame=null}};const updateAutoScroll=y=>{const edge=92;scrollSpeed=y<edge?-Math.max(3,Math.ceil((edge-y)/9)):y>innerHeight-edge?Math.max(3,Math.ceil((y-(innerHeight-edge))/9)):0;if(scrollSpeed&&!scrollFrame){const tick=()=>{if(!scrollSpeed){scrollFrame=null;return}window.scrollBy(0,scrollSpeed);scrollFrame=requestAnimationFrame(tick)};scrollFrame=requestAnimationFrame(tick)}};const activate=()=>{draggingNow=true;dragging=id;el.classList.add('dragging');if(isTouch)toast('Hold near screen edge to scroll')};if(isTouch)holdTimer=setTimeout(activate,280);const moveEv=ev=>{if(!draggingNow){if(!isTouch&&Math.hypot(ev.clientX-startX,ev.clientY-startY)>=9)activate();else if(isTouch&&Math.hypot(ev.clientX-startX,ev.clientY-startY)>=10){clearTimeout(holdTimer);return;}else return;}ev.preventDefault();updateAutoScroll(ev.clientY);const hit=document.elementFromPoint(ev.clientX,ev.clientY);clearOver();el.classList.add('dragging');const target=hit?.closest('.merge-drop')?.closest('.task');const zone=hit?.closest('.drop-zone');if(target&&target!==el)target.classList.add('over');else if(zone)zone.classList.add('drag-target')};const finish=ev=>{clearTimeout(holdTimer);stopAutoScroll();document.removeEventListener('pointermove',moveEv);document.removeEventListener('pointerup',finish);document.removeEventListener('pointercancel',finish);if(!draggingNow)return;const hit=document.elementFromPoint(ev.clientX,ev.clientY),target=hit?.closest('.merge-drop')?.closest('.task'),zone=hit?.closest('.drop-zone');el.classList.remove('dragging');dragging=null;if(zone)move(id,zone.dataset.zone,zone.dataset.section,zone.dataset.lane,target?.dataset.id);clearOver()};document.addEventListener('pointermove',moveEv,{passive:false});document.addEventListener('pointerup',finish,{once:true});document.addEventListener('pointercancel',finish,{once:true});}
  function showForm(defaults={}){const d={kind:'priority',date:today(),lane:'top',...defaults};modal(`<h2>New task</h2><form id="taskForm" class="form-grid"><label>Task name<input required autofocus name="title" placeholder="What needs to happen?"></label><div class="twocol"><label>Quadrant<select name="kind">${['priority','scheduled','recurring','rhythm'].map(x=>`<option ${d.kind===x?'selected':''} value="${x}">${{priority:'Priorities',scheduled:'Scheduled priority',recurring:'Recurring task',rhythm:'Daily rhythm'}[x]}</option>`).join('')}</select></label><label>Date<input name="date" type="date" value="${d.date}"></label></div><div class="twocol"><label>Time (optional)<input name="time" type="time"></label><label>Cadence<select name="cadence"><option value="">Does not repeat</option><option value="daily">Daily</option><option value="weekdays">Every weekday</option><option value="weekends">Every weekend day</option><option value="weekly">Weekly</option><option value="biweekly">Every 2 weeks</option><option value="monthly">Monthly</option><option value="quarterly">Every 3 months</option><option value="yearly">Yearly</option><option value="custom">Custom interval</option></select></label></div><div class="twocol"><label>Custom interval (days)<input name="customDays" type="number" min="1" placeholder="Only for custom"></label><label>Home rhythm section<select name="homeSection"><option value="">None</option>${SECTIONS.map(s=>`<option>${s}</option>`).join('')}</select></label></div><label>Hour slot<select name="lane"><option value="top">First hour</option><option value="bottom">Second hour</option></select></label><div class="form-actions"><button type="button" class="secondary close">Cancel</button><button class="primary">Add task</button></div></form>`,()=>{$('#taskForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),kind=f.get('kind'),cadence=f.get('cadence');const t={id:uid(),title:f.get('title').trim(),kind,date:f.get('date'),time:f.get('time'),cadence:cadence||'',customDays:Math.max(1,Number(f.get('customDays'))||1),homeSection:f.get('homeSection'),lane:f.get('lane'),createdAt:today(),completed:[]};if(kind==='priority')delete t.date;if(kind==='rhythm'&&!t.homeSection)t.homeSection=SECTIONS[timeSection()];if(cadence&&kind!=='recurring'&&kind!=='rhythm')t.kind='recurring';if(t.kind==='recurring'&&cadence==='weekdays')t.date=nextMatchingOnOrAfter(t.date,d=>d.getDay()>0&&d.getDay()<6);if(t.kind==='recurring'&&cadence==='weekends')t.date=nextMatchingOnOrAfter(t.date,d=>d.getDay()===0||d.getDay()===6);state.tasks.push(t);save();const willReveal=t.kind==='rhythm';if(willReveal)revealSection=t.homeSection;closeModal();render();if(!willReveal)toast('Added to Ease')}})}
  function showMenu(id){const t=state.tasks.find(x=>x.id===id);const past=overdue(t),canReschedule=t.kind==='scheduled'||t.kind==='recurring',canEditCadence=t.kind==='recurring';modal(`<h2>${escape(t.title)}</h2><div class="menu">${canReschedule?'<button data-action="reschedule">Reschedule…</button>':''}${canEditCadence?'<button data-action="cadence">Edit cadence…</button>':''}${past?`<button data-action="nextDay">Next day</button><button data-action="nextWeek">Next week, same day</button><button data-action="nextOpen">Next open day</button><button data-action="nextMonth">Next month, same date</button><button data-action="custom">Custom date…</button><button data-action="skip">Skip</button>`:''}<button data-action="home">Set permanent rhythm home…</button><button data-action="unmerge">Remove today’s merge</button><button data-action="delete" class="delete">Delete task</button><button class="close">Cancel</button></div>`,()=>document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>menuAction(id,b.dataset.action)))}
  function showReschedule(id){const t=state.tasks.find(x=>x.id===id);if(!t)return;const skip=t.kind==='recurring'?'<button data-action="skip">Skip this occurrence</button>':'';modal(`<h2>Reschedule ${escape(t.title)}</h2><div class="menu"><button data-action="nextDay">Next day</button><button data-action="nextWeek">Next week, same day</button><button data-action="nextOpen">Next open day</button><button data-action="nextMonth">Next month, same date</button><button data-action="custom">Choose a date…</button>${skip}<button class="close">Cancel</button></div>`,()=>document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>menuAction(id,b.dataset.action)))}
  function cadenceOptions(current){return [['daily','Daily'],['weekdays','Every weekday'],['weekends','Every weekend day'],['weekly','Weekly'],['biweekly','Every 2 weeks'],['monthly','Monthly'],['quarterly','Every 3 months'],['yearly','Yearly'],['custom','Custom interval']].map(([value,text])=>`<option value="${value}" ${current===value?'selected':''}>${text}</option>`).join('')}
  function showCadence(id){const t=state.tasks.find(x=>x.id===id);if(!t)return;modal(`<h2>Edit cadence</h2><form id="cadenceForm" class="form-grid"><label>Repeats<select name="cadence">${cadenceOptions(t.cadence)}</select></label><label>Custom interval (days)<input name="customDays" type="number" min="1" value="${t.customDays||1}"></label><div class="form-actions"><button type="button" class="secondary close">Cancel</button><button class="primary">Save cadence</button></div></form>`,()=>{$('#cadenceForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);t.cadence=f.get('cadence');t.customDays=Math.max(1,Number(f.get('customDays'))||1);if(t.cadence==='weekdays')t.date=nextMatchingOnOrAfter(t.date,d=>d.getDay()>0&&d.getDay()<6);if(t.cadence==='weekends')t.date=nextMatchingOnOrAfter(t.date,d=>d.getDay()===0||d.getDay()===6);save();closeModal();render();toast('Cadence updated')}})}
  function menuAction(id,action){const t=state.tasks.find(x=>x.id===id);if(action==='reschedule'){closeModal();showReschedule(id);return}if(action==='cadence'){closeModal();showCadence(id);return}if(action==='delete'){state.tasks=state.tasks.filter(x=>x.id!==id);delete state.placements[today()]?.[id]}else if(action==='home'){const choice=prompt('Permanent home section:\n'+SECTIONS.join('\n'),t.homeSection||sectionFor(t)||'');if(SECTIONS.includes(choice)){t.homeSection=choice;t.kind='rhythm';delete state.placements[today()]?.[id];toast('Permanent home updated')}else return}else if(action==='unmerge'){const day=state.placements[today()]||{},children=state.tasks.filter(x=>day[x.id]?.merge===id);if(day[id]?.merge){delete day[id].merge;toast('Task separated')}else if(children.length){children.forEach(x=>delete day[x.id].merge);toast('Tasks separated')}else return}else if(action==='custom'){const d=prompt('New due date (YYYY-MM-DD)',today());if(!/^\d{4}-\d\d-\d\d$/.test(d))return;t.date=d}else if(action==='skip'){t.date=nextDate(today(),t.cadence||'daily',t.customDays)}else {t.date=action==='nextDay'?addDays(today(),1):action==='nextWeek'?addDays(today(),7):action==='nextMonth'?nextDate(today(),'monthly'):nextOpenDay();}save();closeModal();render();}
  function nextOpenDay(){let d=addDays(today(),1);while(state.tasks.some(t=>t.id!==undefined&&t.date===d&&!completed(t)))d=addDays(d,1);return d}
  function modal(inner,after){const m=document.createElement('div');m.className='modal-backdrop';m.id='modal';m.innerHTML=`<div class="sheet">${inner}</div>`;document.body.append(m);m.onclick=e=>{if(e.target===m)closeModal()};m.querySelectorAll('.close').forEach(x=>x.onclick=closeModal);after?.()}
  function closeModal(){$('#modal')?.remove()}
  render();
  if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();
